config/routes.rb
Rails.application.routes.draw do
	
  devise_for :users
  root 'pages#home'

  get 'about' => 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
validates :content, presence: true, length: {minimum: 4, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <%= link_to '<i class="fa fa-circle-o-notch"></i> Taskr'.html_safe, root_path, class: 'navbar-brand' %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to 'Account Settings', edit_user_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Log in', new_user_session_path %></li>
        <% end %>
      </ul>
      </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class = 'container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<h3>Helping you improve your productivity</h3>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1><i class="fa fa-circle-o-notch"></i> Taskr</h1>
  <p>Helping you increase your productivity!</p>
  <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
</div>